### ISSUE TITLE
Unable to resolve path to module 'tinyws'

### ISSUE THREAD

**Issue by mattfeury** [tinyhttp/tinyws#11] opened 2022-12-28 17:50 UTC
hello, 

attempting to switch over to this project from express-ws. i followed the express example here: https://github.com/tinyhttp/tinyws/pull/7/files

however on `npm run build`, i am getting the following eslint error: 

```
    7:24  error    Unable to resolve path to module 'tinyws'                               import/no-unresolved
```

this is on the line

```
import { tinyws } from 'tinyws';
```

did not see this referenced anywhere, so wanted to share here in case others have seen it. 

looks like i had to follow this post: https://stackoverflow.com/a/68661168/1137921 and add `eslint-import-resolver-typescript` and some eslint settings. wanted to share here in case others come across this

**Comment by talentlessguy** [comment] 2022-12-28 18:36
is there something wrong with the project configuration / bundling? it always worked and CI passes (including typecheck and build)

**Comment by mattfeury** [comment] 2022-12-28 19:17
not to my knowledge but i suppose "wrong" is subjective :). this is a pretty standard node/typescript project that i've used plenty of other typescript modules in before without issue. happy to share specific pieces of code if you are interested in something particular

**Comment by talentlessguy** [comment] 2023-01-05 22:46
@mattfeury I meant with tinyws

**Comment by mattfeury** [comment] 2023-01-05 23:00
not sure tbh. have not looked at the source code much – just had some trouble out of the box here so moved past this project. if i come back to it and discover anything, i'll be sure to update.

**Comment by talentlessguy** [comment] 2023-05-08 10:49
closing for now because can;t reproduce

**Comment by mattvb91** [comment] 2023-06-22 09:39
Same problem here using with typescript. @mattfeury what did you switch to?

**Comment by talentlessguy** [comment] 2023-06-22 10:24
this issue is not related to tinyws, it's an eslint-plugin-import bug (or some other plugin)

**Comment by mattfeury** [comment] 2023-06-22 14:33
> Same problem here using with typescript. @mattfeury what did you switch to?

we switched to express-ws

**Comment by mattvb91** [comment] 2023-06-22 16:42
> this issue is not related to tinyws, it's an eslint-plugin-import bug (or some other plugin)

I dont have any eslint plugins in my project just tried to install this and use it.

**Comment by talentlessguy** [comment] 2023-06-22 16:46
> > this issue is not related to tinyws, it's an eslint-plugin-import bug (or some other plugin)
> 
> I dont have any eslint plugins in my project just tried to install this and use it.

could you please give me reproduction steps so I replicate the issue on my end?

**Closed** 2024-01-06 22:25 UTC
Labels: can't reproduce
